config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'

  get 'about' => 'pages#about'

  get 'contactus' => 'pages#contactus'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<hr />
<br />
&copy 2016 FinHunt

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <a class="navbar-brand" href="/">FinHunt</a>
  <ul class="nav navbar-nav">
    <li class="nav-item active">
      <%= link_to "home", root_path %>
    </li>
    <li class="nav-item">
      <%= link_to "about", about_path %>
    </li>
    <li class="nav-item">
      <%= link_to "contact", contactus_path %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinHunt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>



    <div class="container">
        <%= render 'layouts/navbar' %>
        <br />
        <br />
        <%= yield %>
        <br />
        <br />
        <%= render 'layouts/footer' %>
    </div>



  </body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>FinHunt surfaces the best new products, every day.
  It's a place for product-loving enthusiasts to share
  and geek out about the latest mobile apps,
  websites, hardware projects, and tech creations.</p>

app/views/pages/contactus.html.erb
<h1>Contact Us</h1>
<p>We're working on FinHunt right now. You can send us tips and news
at twitter.com/<a href="https://twitter.com/wisesumo">wisesumo</a></p>

app/views/pages/home.html.erb
<h1>The hottest news on finance and banking tech </h1>
<p>FinHunt is a curation of the best new FinTech startup, every day.
   Discover the latest mobile apps, websites, and technology products
  that everyone's talking about.</p>